# ~/ansible-project/playbook.yml
- name: Установка nginx через роль
  hosts: all
  become: true

  vars:
    nginx_package_name: nginx

  roles:
    - role: install_nginx
      tags: nginx



- name: Плейбук c ролью приветствия
  hosts: localhost
  gather_facts: false
  roles:
    - role: say_hello
      tags: hello