- name: Display dp
  debug:
    var: dp
  become: yes

- name: Display dp name
  debug:
    msg: "{{ dp_name }}"
  become: yes

- name: Debug path and account
  debug:
    msg:
      - "path = {{ dp.path }}"
      - "account = {{ dp.account }}"

