- name: Display dp
  debug:
    var: dp
  become: yes

- name: Display dp name
  debug:
    msg: "{{ dp_name }}"
  become: yes

- name: Debug path and account
  debug:
    msg:
      - "path = {{ dp.path }}"
      - "account = {{ dp.account }}"

- name: Debug regex
  debug:
    msg:
      - "path = {{ dp.path }}"
      - "account = {{ dp.account }}"
  vars:
    filter: "{{ dp.filter | default('') | regex_escape }}"
    hdfs_base: "{{ dp.path | regex_replace(filter ~ '$'', '') }}"
    relative_path: "{{  }}"

- name: Create ok file
  command:
    cmd: echo "Processing {{ dp_name }}" > "{{ dp_name }}_ok.txt"
  register: process_result
  failed_when: process_result.rc != 0

- name: Check if ok file exists for {{ dp_name }}
  stat:
    path: "{{ dp_name }}_ok.txt"
  register: file_check_result

- name: Debug file_check_result
  debug:
    msg: "file_check_result: {{ file_check_result }}"

- name: Pass result back to main.yml
  set_fact:
    task_results: "{{ task_results + [file_check_result.stat] }}"

- name: Parse exclude paths
  set_fact:
    exclude_paths_list: "{{ dp.exclude_paths | default('') | split(';') | reject('equalto', '') | list }}"

- name: Ensure filter file exists and is empty
  copy:
    dest: /tmp/distcp_filter.txt
    content: ""
    mode: '0644'

- name: Debug exclude_paths_list
  debug:
    msg: "exclude_paths_list: {{ exclude_paths_list }}"

- name: Add exclude paths to the filter file 
  lineinfile:
    path: /tmp/distcp_filter.txt
    line: "{{ item }}"
    insertafter: EOF
  loop: "{{ exclude_paths_list }}"
  when: dp.exclude_paths | lenght > 0