---
# - name: Remove file in /tmp/dp
#   file:
#     path: "/tmp/dp"
#     state: absent
#   become: yes

# - name: Create dir /tmp/dp
#   file:
#     path: "/tmp/dp/"
#     state: absent
#     mode: "0775"
#   become: yes


- name: Copy file
  copy:
    src: files/data.json
    dest: "/tmp/dp/data.json"
  become: yes

- name: Read json
  slurp:
    src: "/tmp/dp/data.json"
  register: data_file
  become: yes

- name: Covert JSON
  set_fact:
    data: "{{ data_file['content'] | b64decode | from_json }}"
  become: yes

- name: Extract one dp
  set_fact:
    dp: "{{ data.resources | selectattr('dp3', 'defined') | map(attribute='dp3') | list }}"
  become: yes

- name: Display dp
  debug:
    var: dp
  become: yes

- name: Display dp path
  debug:
    msg: "{{ dp[0].path }}"
  become: yes

- name: Set dp vars
  set_fact:
    path: "{{ dp[0].path }}"
    account: "{{ dp[0].account }}"

- name: Display dp details
  ansible.builtin.shell: |
    echo "path: {{ path }}"
    echo "account: {{ account }}"
  become: yes