---
# - name: Remove file in /tmp/dp
#   file:
#     path: "/tmp/dp"
#     state: absent
#   become: yes

- name: Create dir /tmp/dp
  file:
    path: "/tmp/dp/"
    state: directory
    mode: "0775"
  become: yes

- name: Prepare vars
  set_fact:
    success_list: []
    failure_list: []
    task_results: []
  become: yes

- name: Copy file
  copy:
    src: files/data.json
    dest: "/tmp/dp/data.json"
  become: yes

- name: Read json
  slurp:
    src: "/tmp/dp/data.json"
  register: data_file
  become: yes

- name: Covert JSON
  set_fact:
    data: "{{ data_file['content'] | b64decode | from_json }}"
  become: yes

# - name: Extract one dp
#   set_fact:
#     dp: "{{ data.resources | selectattr('dp3', 'defined') | map(attribute='dp3') | list }}"
#   become: yes

- name: Load variables from JSON
  include_vars:
    file: files/data.json

- name: Display sources
  debug:
    var: sources
  become: yes

- name: Run task file only for sources that are enabled
  block:
    - name: Run 01_flow
      include_tasks: "tasks/01_flow.yml"
      vars:
        dp: "{{ source.value }}"
        dp_name: "{{ source.key }}"
      loop: "{{ sources | map('dict2items') | map('first') | list }}"
      loop_control:
          loop_var: source

    - name: Check if ok file exists for {{ dp_name }}
      stat:
        path: "{{ dp_name }}_ok.txt"
      loop: "{{ sources | map('dict2items') | map('first') | list }}"
      loop_control:
          loop_var: source
      register: file_check_result

  when: source.value.skip_generic_flow | default("no") == "no"
  # vars:
  #   dp: "{{ source.value }}"
  #   dp_name: "{{ source.key }}"
    # register: task_results

- name: Debug file_check_result
  debug:
    msg: "file_check_result: {{ file_check_result }}"

- name: Update success_list
  set_fact:
    success_list: "{{ success_list + [item.item.name] }}"
  with_items: "{{ file_check_result.results }}"
  when: file_check_result.results[loop.index0].stat.exists

- name: Update failure_list
  set_fact:
    failure_list: "{{ failure_list + [item.item.name] }}"
  with_items: "{{ task_results.results }}"
  when: not file_check_result.results[loop.index0].stat.exists

- name: Print summary
  debug:
    msg: |
      Summary:
      Successful entries: {{ success_list }}
      Failed entries: {{ failure_list }}


# - name: Display dp
#   debug:
#     var: dp
#   become: yes

# - name: Display dp path
#   debug:
#     msg: "{{ dp[0].path }}"
#   become: yes

# - name: Set dp vars
#   set_fact:
#     path: "{{ dp[0].path }}"
#     account: "{{ dp[0].account }}"

# - name: Debug path and account
#   debug:
#     msg:
#       - "path = {{ path }}"
#       - "account = {{ account }}"


# - name: Display dp details
#   ansible.builtin.shell: |
#     echo "path: {{ path }}"
#     echo "account: {{ account }}"
#   when:
#     - dp is defined

# - name: Display dp details via shell
#   shell: |
#     echo "PATH={{ path }}"
#     echo "ACCOUNT={{ account }}"
#   register: dp_shell_output
#   vars:
#     path: "{{ dp[0].path }}"
#     account: "{{ dp[0].account }}"
#   become: yes

# - name: Show captured shell output
#   debug:
#     var: dp_shell_output.stdout_lines
